### ISSUE TITLE
SRP requests

### ISSUE THREAD

**Issue by Dentonan** [KryptedGaming/krypted#284]
As a corp we offer SRP for fleets, we would like an option for line members to post an srp request, linking their Zkil and providing info about the loss
then assign roles to people to look through srp requests and approve/deny them, options of providing feedback.

another usefule feature would be to allow us to decide default payouts for certain ships e.g. sabre and have the system auto detect ship and give a reccomended payout.

**Comment by porowns** [comment]
This would be a larger feature request, since this would require an entire module. 

For anybody looking to tackle this, fork our [package template](https://github.com/KryptedGaming/django-package-template) and follow something similar to the [timerboards](https://github.com/KryptedGaming/django-eveonline-timerboard) package.

**Comment by porowns** [comment]
In progress, moved to https://github.com/KryptedGaming/django-eveonline-doctrine-manager/issues/5
